name: Defender Bot Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download dependencies
        env:
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          bash scripts/defender-bot.sh --proxy "$PROXY_URL"
